### ISSUE TITLE
V1.2.12 Crash at startup

### ISSUE THREAD

**Issue by cesar300** [bibendovsky/bstone#435]
I had copied the executable into the gog installation.
![Sin título](https://user-images.githubusercontent.com/43586856/193458343-7720c8e6-4dd2-4417-b106-753c7e5f2f87.png)
What's going on?

**Comment by bibendovsky** [comment]
Does the following build resolves the issue?

[bstone_windows_x64_v1_2_13-wip-78659193085fc0b497720f97d76734e5ac720528.zip](https://github.com/bibendovsky/bstone/files/9739453/bstone_windows_x64_v1_2_13-wip-78659193085fc0b497720f97d76734e5ac720528.zip)
[bstone_windows_x86_v1_2_13-wip-78659193085fc0b497720f97d76734e5ac720528.zip](https://github.com/bibendovsky/bstone/files/9739454/bstone_windows_x86_v1_2_13-wip-78659193085fc0b497720f97d76734e5ac720528.zip)

Changes related to rendering:
- Just clear the screen inside vid_check_vsync.

**Comment by cesar300** [comment]
Still not. Same error.

**Comment by johnsant65** [comment]
Same error here. Works fine in 1.2.11, so introduced since then.

Software mode is fine, but all OpenGL modes crash.

**Comment by bibendovsky** [comment]
Managed to reproduce the issue in VMware Workstation Player.

Fixed binaries:
[bstone_v1.2.13-wip-i686-099dde62df583b58b8cc9ff06ac7791628696ce5.zip](https://github.com/bibendovsky/bstone/files/14536847/bstone_v1.2.13-wip-i686-099dde62df583b58b8cc9ff06ac7791628696ce5.zip)
[bstone_v1.2.13-wip-x86_64-099dde62df583b58b8cc9ff06ac7791628696ce5.zip](https://github.com/bibendovsky/bstone/files/14536851/bstone_v1.2.13-wip-x86_64-099dde62df583b58b8cc9ff06ac7791628696ce5.zip)

Feel free to reopen the issue if the binaries not helped.

**Comment by Tricky1975** [comment]
For me the issue was not fixed. Unfortunately.
![image](https://github.com/bibendovsky/bstone/assets/11202073/1dc3375a-8f73-4cb9-98c1-52a2b82bc355)
